# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'streetParker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_modular_headers!
   use_frameworks!

  # Pods for streetParker
    
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'MapboxNavigation'
   pod 'FBSDKLoginKit/Swift'
   pod 'FBSDKLoginKit/Swift'
   pod 'FBSDKCoreKit/Swift'
   pod 'FBSDKShareKit/Swift'
   pod 'GoogleSignIn'
end
